export interface DashboardAlert {
  id: string;
  type: 'error' | 'warning' | 'info';
  message: string;
  assignmentId: string;
  submissionId: string | null;
}

export interface StudentSummary {
  assignmentCount: number;
  submittedCount: number;
  gradedCount: number;
  needsActionCount: number;
  nextDueAssignment: {
    assignmentId: string;
    title: string;
    dueAt: string | null;
    dueLabel: string;
    dueRelativeLabel: string;
    status: 'none' | 'submitted' | 'processing' | 'graded' | 'failed';
    submissionId: string | null;
    grade: StudentAssignmentSummary['grade'];
  } | null;
  alerts: DashboardAlert[];
}

export interface StudentAssignmentSummary {
  assignmentId: string;
  title: string;
  totalMarks: number;
  dueAt: string | null;
  dueLabel: string;
  dueRelativeLabel: string;
  isClosed: boolean;
  isOverdue: boolean;
  canSubmit: boolean;
  needsAction: boolean;
  canResubmit: boolean;
  submission: {
    submissionId: string | null;
    status: 'none' | 'submitted' | 'processing' | 'graded' | 'failed';
    submittedAt: string | null;
  };
  grade: {
    score: number | null;
    maxScore: number | null;
    percentage: number | null;
    flags: string[];
    updatedAt: string | null;
  } | null;
}

export interface RecentGradeItem {
  gradeId: string;
  assignmentId: string;
  submissionId: string;
  title: string;
  score: number;
  maxScore: number;
  percentage: number;
  updatedAt: string;
  flags: string[];
  submittedAt: string | null;
}

export interface AssignmentDetail {
  assignmentId: string;
  title: string;
  courseName: string;
  description: string;
  instructions: string[];
  requiredDiagramType: string;
  submissionMode: 'uxf' | 'image' | 'unknown';
  acceptedFileTypes: string;
  acceptedFileExtensions: string[];
  uploadPrompt: string;
  submissionFormatRules: string[];
  namingGuidance: string;
  markingNote: string;
  totalMarks: number;
  dueAt: string | null;
  dueLabel: string;
  dueRelativeLabel: string;
  isClosed: boolean;
  isOverdue: boolean;
  timeRemainingLabel: string;
  attemptRule: string;
  submission: {
    submissionId: string;
    status: 'none' | 'submitted' | 'processing' | 'graded' | 'failed';
    submittedAt: string;
    imageUrl: string;
    originalFileName: string;
    mimeType: string;
    fileSizeBytes: number;
    extractionError: string | null;
  } | null;
  grade: {
    gradeId: string;
    score: number;
    maxScore: number;
    percentage: number;
    breakdown: {
      criterionKey: string;
      label: string;
      maxMarks: number;
      awardedMarks: number;
      reason?: string;
    }[];
    discrepancies: {
      category: string;
      severity: string;
      message: string;
      expected?: string;
      actual?: string;
      entityRef?: string;
    }[];
    flags: string[];
    updatedAt: string;
    teacherFinalScore: number | null;
    teacherComment: string | null;
    chosenSolutionLabel: string | null;
    confidenceScore: number | null;
  } | null;
  canSubmit: boolean;
  canResubmit: boolean;
  attemptsUsed: number;
  attemptsRemaining: number;
  attemptsHistory: {
    attemptNumber: number;
    submissionId: string;
    submittedAt: string;
    status: 'none' | 'submitted' | 'processing' | 'graded' | 'failed';
    autoMark: number | null;
    finalMark: number | null;
    feedbackAvailable: boolean;
  }[];
  summary: {
    currentStatus: string;
    lastSubmissionTime: string | null;
    bestMark: number | null;
    latestMark: number | null;
    finalMark: number | null;
    finalMarkShown: boolean;
    lateStatus: string;
  };
  latestResult: {
    gradingStatus: string;
    automatedMark: number | null;
    finalTeacherMark: number | null;
    bestMatchedSolutionLabel: string;
    shortFeedbackSummary: string;
    confidenceScore: number | null;
  };
  feedback: {
    teacherFeedback: string | null;
    autoGeneratedFeedbackSummary: string;
    strengthsDetected: string[];
    missingComponents: string[];
    incorrectRelationships: string[];
    namingIssues: string[];
    suggestions: string[];
  };
}

export interface SubmissionDetail {
  submissionId: string;
  assignment: {
    assignmentId: string;
    title: string;
    totalMarks: number;
    dueAt: string | null;
    dueLabel: string;
  } | null;
  status: 'none' | 'submitted' | 'processing' | 'graded' | 'failed';
  submittedAt: string;
  createdAt: string;
  imageUrl: string;
  originalFileName: string;
  mimeType: string;
  fileSizeBytes: number;
  extractionError: string | null;
  grade: AssignmentDetail['grade'];
}

export function formatStatusLabel(status: StudentAssignmentSummary['submission']['status']) {
  switch (status) {
    case 'none':
      return 'Not submitted';
    case 'submitted':
      return 'Submitted';
    case 'processing':
      return 'Grading in progress';
    case 'graded':
      return 'Graded';
    case 'failed':
      return 'Failed';
    default:
      return status;
  }
}

export function formatDateTime(value?: string | null) {
  if (!value) {
    return 'No due date';
  }

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return 'Unknown date';
  }

  return date.toLocaleString();
}

export function formatCompactDate(value?: string | null) {
  if (!value) {
    return 'No due date';
  }

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return 'Unknown date';
  }

  return date.toLocaleDateString(undefined, {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

export function formatFileSize(bytes: number) {
  if (bytes < 1024) {
    return `${bytes} B`;
  }

  const kb = bytes / 1024;
  if (kb < 1024) {
    return `${kb.toFixed(1)} KB`;
  }

  return `${(kb / 1024).toFixed(1)} MB`;
}
