export interface TeacherAssignmentDetail {
  assignment: {
    assignmentId: string;
    title: string;
    description: string;
    totalMarks: number;
    dueAt: string | null;
    createdAt: string;
    updatedAt: string;
    status: 'Draft' | 'Open' | 'Closed';
    isPublished: boolean;
    marksPublishedAt: string | null;
    marksPublishedBy: string | null;
  };
  summary: {
    totalSubmissions: number;
    studentsGraded: number;
    pendingGrading: number;
    averageMark: number | null;
    highestMark: number | null;
    lowestMark: number | null;
    lateSubmissionsCount: number;
    referenceSolutionsUploaded: number;
  };
  referenceSolutions: {
    activeCount: number;
    hasSynonymMapConfigured: boolean;
    lastExtractionAt: string | null;
    items: ReferenceSolutionItem[];
  };
  synonymsConfig: {
    isConfigured: boolean;
    preview: { term: string; aliases: string[] }[];
    matchingRulesSummary: string[];
    allowedEquivalentNamesCount: number;
  };
  invitedStudents: {
    totalInvited: number;
    registeredCount: number;
    pendingCount: number;
    items: {
      email: string;
      status: 'Registered' | 'Pending';
      studentId: string | null;
      fullName: string | null;
    }[];
  };
  submissions: SubmissionRow[];
  analytics: {
    markDistribution: { range: string; count: number }[];
    matchedSolutions: { slot: string; count: number }[];
    commonMistakes: { message: string; count: number }[];
    mostFrequentlyMissedClass: { label: string; count: number } | null;
    mostCommonRelationshipError: { label: string; count: number } | null;
    submissionsNeedingManualReview: number;
  };
  actions: {
    canEditAssignment: boolean;
    canCloseAssignment: boolean;
    canDeleteAssignment: boolean;
    canExportMarksCsv: boolean;
    canPublishMarks: boolean;
  };
  activity: {
    type: string;
    occurredAt: string;
    message: string;
  }[];
}

export interface ReferenceSolutionItem {
  solutionId: string;
  slot: string;
  label: string;
  originalFileName: string;
  mimeType: string;
  fileSizeBytes: number;
  previewUrl: string;
  extractionStatus: 'ready' | 'failed' | 'processing';
  extractionStatusLabel: string;
  extractedStructure: unknown;
  extractionError: string | null;
  lastExtractionAt: string | null;
  updatedAt: string;
  uploadedAt: string;
  hasSynonymMapConfigured: boolean;
}

export interface SubmissionRow {
  submissionId: string;
  studentName: string;
  studentEmail: string;
  studentId: string;
  submittedAt: string;
  status: 'submitted' | 'processing' | 'graded' | 'failed';
  autoMark: number | null;
  maxScore: number;
  percentage: number | null;
  bestMatchedSolution: {
    slot: string;
    label: string;
  } | null;
  confidenceScore: number | null;
  isLate: boolean;
  needsReview: boolean;
  flags: string[];
  detail: {
    imageUrl: string;
    originalFileName: string;
    mimeType: string;
    fileSizeBytes: number;
    extractionError: string | null;
    autoGeneratedMark: number | null;
    maxScore: number;
    bestMatchedReferenceSolution: {
      slot: string;
      label: string;
    } | null;
    markingCriteria: {
      criterionKey: string;
      label: string;
      maxMarks: number;
      awardedMarks: number;
      reason?: string;
    }[];
    missingClasses: DiscrepancyItem[];
    extraClasses: DiscrepancyItem[];
    relationshipMismatches: DiscrepancyItem[];
    attributeMethodMismatches: DiscrepancyItem[];
    namingMismatches: DiscrepancyItem[];
    synonymMatchesDetected: DiscrepancyItem[];
    teacherFinalMark: number | null;
    teacherComment: string;
    override: {
      isOverridden: boolean;
      overriddenBy: string | null;
      overriddenAt: string | null;
      originalScore: number | null;
      finalScore: number | null;
    } | null;
  };
}

export interface DiscrepancyItem {
  category: string;
  severity: string;
  message: string;
  expected?: string;
  actual?: string;
  entityRef?: string;
}

export function formatTeacherAssignmentStatus(status: TeacherAssignmentDetail['assignment']['status']) {
  return status;
}

export function formatTeacherSubmissionStatus(status: SubmissionRow['status']) {
  switch (status) {
    case 'graded':
      return 'Graded';
    case 'processing':
      return 'Processing';
    case 'failed':
      return 'Failed';
    case 'submitted':
    default:
      return 'Submitted';
  }
}
